name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com/glebiller'
          scope: '@glebiller'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to GitHub package registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create traball from package
        run: npm pack
      - name: Create GitHub release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Get release tag from git revision
        run: |
          GITHUB_REF=${{ github.ref }}
          GITHUB_TAG=${GITHUB_REF#refs/tags/v}
          echo "$GITHUB_REF -> $GITHUB_TAG"
          echo "GITHUB_TAG=$GITHUB_TAG" >> $GITHUB_ENV
      - name: Upload GitHub assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: glebiller-flux-lens-extension-${{ env.GITHUB_TAG }}.tgz
          asset_name: flux-lens-extension-${{ env.GITHUB_TAG }}.tgz
          asset_content_type: application/octet-stream